### ISSUE TITLE
trained network

### ISSUE THREAD

**Issue by lsgh** [dhammack/DSB2017#8]
Hi Daniel,

Would it be possible to get access to your already trained network without the need to re-do the trainig from scratch?

Thank you!
Laleh

**Comment by dhammack** [comment]
Yes! Pretrained models are available in the scoring_code folder. A word of warning however they were build with an old version of Keras so you may need to downgrade in order to load them properly.

**Comment by qianwangn** [comment]
Can just use your work to make a submission for Luna16?
Do I need additional data?

**Comment by dhammack** [comment]
Hi John. My models can be used to make a submission to LUNA16. However it probably won't work 'out of the box' and will require some additional work. Furthermore my models were trained on all the LUNA data, not using the 10-fold cross validation that they request. So you would at a minimum need to retrain the models.
